<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Session 2 : Understanding the scores of one habit using the t-test</title>

<script src="site_libs/header-attrs-2.21/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-6.4.0/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.0/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">L'Institut Agro Rennes Angers & Seoul National University: a bottom-up approach to statistical analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/AgrocampusDS/demarche_statistique">
    <span class="fa fa-github"></span>
     
    
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Session 2 : Understanding the scores of one
habit using the t-test</h1>

</div>


<div id="section"
class="section level1 tabset tabset-fade tabset-pills">
<h1 class="tabset tabset-fade tabset-pills"></h1>
<div id="objectives-of-this-session" class="section level2">
<h2>Objectives of this session</h2>
</div>
<div id="exercises" class="section level2">
<h2>Exercises</h2>
<div
id="is-the-habit-of-becoming-vegetarian-a-constraint-on-peoples-everyday-lives"
class="section level3">
<h3>Is the habit of becoming vegetarian a constraint on people’s
everyday lives?</h3>
<p>Let’s look first at the habit of becoming vegetarian. The first
research question you can formulate from these data is: ‘Is the habit of
becoming vegetarian a constraint in people’s everyday lives? If the
answer to this question is ’no’, then the scores given by the
respondents in the questionnaire should be around 0.</p>
<p>We will answer this research question by using the t-test, which
checks whether the <em>true</em> mean of the score is 0 or not. On the
one hand, we have observed data from which we derive an empirical mean
that is supposed to reflect a theoretical mean <span
class="math inline">\(\mu\)</span>. We want to compare this theoretical
mean, approximated by our empirical mean, with 0. In other words, we
want to test whether <span class="math inline">\(\mu = 0\)</span> or
not.</p>
<p>A t-test for a reference value (often referred to as a one-sample
t-test) is a statistical hypothesis test used to determine if the mean
of a sample is significantly different from a known reference value.
This test is commonly used when you have a single sample of data and you
want to assess whether the sample’s mean is statistically different from
a specified value that you consider as a reference or benchmark.</p>
<p>However, prior to conducting any analysis, it’s essential to
comprehend the process of inputting data into a dataset. This involves
determining the statistical entities of interest and identifying the
variables.</p>
<p>In practical terms, each of the 167 people questioned evaluated 10
habits: they filled in a form on which they put their identifier, the
habit evaluated and the score on a scale from 0 to 5. In concrete terms,
each of the 167 people questioned evaluated ten habits: they filled in a
form on which they put their identifier, the habit evaluated and the
score of constraint on a scale from 0 to 5. From this point of view,
each form can be considered as a statistical individual on which a
quantitative variable, a score of constraint, and two qualitative
variables, the habit and the assessor’s identifier, were measured.</p>
<p>Let’s have a look at the dimension of our data set and at the first 5
rows.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data_long_score)</span></code></pre></div>
<pre><code>## [1] 1670    3</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data_long_score[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,]</span></code></pre></div>
<pre><code>## # A tibble: 5 × 3
##   Judge Habit                Score
##   &lt;fct&gt; &lt;chr&gt;                &lt;int&gt;
## 1 1     car_alone_score          0
## 2 1     never_airplane_score     5
## 3 1     loaner_score             1
## 4 1     clothes_second_score     2
## 5 1     bulk_score               2</code></pre>
<p>We have 1670 statistical individuals measured by 3 variables. Let’s
limit ourselves to the <em>veggie</em> habit and see if it’s a
constraint.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data_veggie <span class="ot">&lt;-</span> data_long_score[data_long_score<span class="sc">$</span>Habit<span class="sc">==</span><span class="st">&quot;vegetarian_score&quot;</span>,]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(data_veggie)</span></code></pre></div>
<pre><code>## [1] 167   3</code></pre>
<p>We want to see if the 167 scores associated with this habit produce
an empirical mean that reflects a theoretical mean of 0.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data_veggie<span class="sc">$</span>Score)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  data_veggie$Score
## t = 30.096, df = 166, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  3.323548 3.790225
## sample estimates:
## mean of x 
##  3.556886</code></pre>
<p>The only input we have provided to the <code>t.test()</code> function
is the vector of 167 scores. What can we deduce from the output of this
function? Firstly, that the function has tested the equality of our
theoretical mean to 0 against the alternative that the true mean is not
equal to 0. This means that the default value for the reference value is
0. Then that our true mean is not equal to 0, given the confidence
interval around the true mean: 0 does not belong to this interval. By
construction, the empirical mean of the 167 values (3.55) is right in
the middle of our confidence interval around <span
class="math inline">\(\mu\)</span>.</p>
<p>With no further details, let’s generate 167 values from a centred
reduced normal distibution and calculate the means of these values.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">rnorm</span>(<span class="dv">167</span>))</span></code></pre></div>
<pre><code>## [1] -0.1544931</code></pre>
<p>We could do this several times and generate a distribution of
averages calculated from 167 values from a centred reduced normal
distribution. The <em>p-value</em> is the probability of observing the
empirical mean that has actually been observed within this distribution
of averages. In other words, if the theoretical mean is equal to 0, the
probability of observing the mean that was actually observed is zero
(&lt; 2.2e-16).</p>
<p>To understand the very important concept of standard deviation, we
can refer to the concept of proxemics which is the study of how people
perceive and use space in various social and cultural contexts. It deals
with the ways in which individuals structure and interact with their
physical environment, as well as the distances they maintain between
themselves and others during communication and social interactions.</p>
<p>Edward T. Hall, an anthropologist, introduced the concept of
proxemics in the mid-20th century. He categorized the space around
individuals into different zones, such as intimate distance, personal
distance, social distance, and public distance. These zones have
cultural and contextual variations, and they influence how people
interact, communicate, and feel comfortable in different situations.</p>
<p>In statistics we often say that 95% of the population is within 2
standard deviations. With our observations, we are a good 30 standard
deviations of our reference value (<em>t=30.096</em>), which is 0. In
other words, culturally speaking, we are infinitely far from it, to use
the terms of proxemics.</p>
<p>In conclusion, the score of constraint for becoming vegetarian is not
equal to 0, and we can say that this habit is perceived as being
constraining for the participants.</p>
</div>
<div id="is-it-very-constraining" class="section level3">
<h3>Is it very constraining?</h3>
<p>To answer this question, we won’t test for equality at 0, but for
superiority at another reference value, let’s say 3 for the sake of
clarity. To do so, let’s add two arguments to our call to the
<code>t-test()</code> function:</p>
<ul>
<li>First, by setting the argument <code>mu = 3</code>, we can compare
the mean value of the score to the value of 3.</li>
<li>Second, by setting the argument
<code>alternative = "greater"</code>, we can conduct a t-test on whether
the mean is greater than 3.</li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data_veggie<span class="sc">$</span>Score, <span class="at">mu =</span> <span class="dv">3</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  data_veggie$Score
## t = 4.712, df = 166, p-value = 2.581e-06
## alternative hypothesis: true mean is greater than 3
## 95 percent confidence interval:
##  3.361399      Inf
## sample estimates:
## mean of x 
##  3.556886</code></pre>
<p>This t-test has a different null hypothesis/alternative hypothesis
than the t-test we conducted earlier. For the earlier one, the null
hypothesis was that the true mean of the score was equal to 0, while the
alternative hypothesis was that the true mean of the score was not equal
to 0. However, the alternative hypothesis does not specify whether the
true mean of the score is bigger or smaller than 0.</p>
<p>For this t-test, the null hypothesis is that the true mean is equal
to the value that we have chosen, and the alternative hypothesis is that
the true mean is greater than 3.</p>
<p>Several elements of the output indicate that the true mean is greater
than 3, our reference value. The confidence interval around the true
mean does not contain the reference value, but it does contain numbers
greater than our reference value. The <em>p-value</em> is much smaller
than 0.05, meaning that we can reject the null hypothesis, and accept
the alternative hypothesis.</p>
<p>In conclusion, we can evaluate the habit of becoming vegetarian is
perceived as very constraining.</p>
</div>
<div id="now-its-your-turn" class="section level3">
<h3>Now it’s your turn!</h3>
<p>Let’s do the same thing with the variable
<em>air_drying_score</em>.</p>
<p>Is air-drying more constraining than becoming vegetarian? We’ll
answer that question in the next session.</p>
</div>
</div>
<div id="vocabulary-of-this-session" class="section level2">
<h2>Vocabulary of this session</h2>
<div id="r-commands" class="section level3">
<h3>R commands</h3>
<ul>
<li>library</li>
</ul>
</div>
<div id="r-environment" class="section level3">
<h3>R environment</h3>
<ul>
<li>packages</li>
</ul>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
