<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Session 3 : Comparing the scores of two habits using the t-test</title>

<script src="site_libs/header-attrs-2.21/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-6.4.0/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.0/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">L'Institut Agro Rennes Angers & Seoul National University: a bottom-up approach to statistical analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/AgrocampusDS/demarche_statistique">
    <span class="fa fa-github"></span>
     
    
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Session 3 : Comparing the scores of two
habits using the t-test</h1>

</div>


<div id="section"
class="section level1 tabset tabset-fade tabset-pills">
<h1 class="tabset tabset-fade tabset-pills"></h1>
<div id="objectives-of-this-session" class="section level2">
<h2>Objectives of this session</h2>
</div>
<div id="exercises" class="section level2">
<h2>Exercises</h2>
<p>Remember that in the previous session we made our decision on the
basis of a confidence interval, a distribution of averages, a number of
steps relative to a reference situation: we can’t make a decision on the
basis of a single value such as the average. Individual data are
essential because we need to incorporate the notion of variability into
our decision making.</p>
<p>In this session, for technical reasons that we will explain later, we
will first look at how to compare two variances with each other, and
then we will see how the results of this variance comparison can be used
to compare two means with each other.</p>
<p>We will look at the habits of never flying on an airplane, and
unplugging one’s electrical devices when you are not using it.</p>
<div id="comparing-two-variances" class="section level3">
<h3>Comparing two variances</h3>
<p>In order to filter out the data for scores for never flying an
airplane, and unplugging one’s electrical devices, we will use the
<code>filter()</code> function to filter out the habits that we are
trying to compare and saving it to another data frame.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_plane_unplug <span class="ot">&lt;-</span> data_long_score <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Habit <span class="sc">==</span> <span class="st">&quot;never_airplane_score&quot;</span><span class="sc">|</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                                                Habit <span class="sc">==</span> <span class="st">&quot;unplug_score&quot;</span>)</span></code></pre></div>
<p>Two values can be compared either by calculating their difference or
by calculating their ratio. Comparing two variances is done by
calculating the ratio of these two variances. Since the variance is a
sum of squares, the ratio of two variances follows a certain
distribution when the variances are equal.</p>
<p>For this comparison, we’ll use the same proof by contradiction that
we used in the previous session. A proof of contradiction is a logical
reasoning in which a proposition is proven true by assuming its opposite
(contradiction) and then showing that this assumption leads to an absurd
or contradictory result. This method helps establish the truth of the
original proposition by showing that its negation cannot hold without
leading to logical inconsistencies.</p>
<p>In our case, we’ll calculate the ratio of two variances and then
check whether this ratio falls within the expected distribution when the
variances are equal: that is the idea behind the very important F-test.
Let’s compare our variances with the <code>var.test()</code>
function.</p>
<p>Our dataset <em>data_plane_unplug</em> comprises three variables: one
quantitative variable representing different scores, and two qualitative
variables—one for identifying the habit and another for identifying the
assessor. Comparing the variances associated with the two habits raises
the question of whether the variance depends on the habits or not.</p>
<p>Thus, when using the <code>var.test()</code> function for comparing
variances in R, you need to provide two arguments: the formula that
expresses the relationship or dependency and the name of the
dataset.</p>
<p>In the R programming language, the tilde character (~) is used to
represent dependency or relationships between variables, especially in
the context of modeling or formula specifications.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(Score <span class="sc">~</span> Habit, data_plane_unplug)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  Score by Habit
## F = 1.2669, num df = 166, denom df = 166, p-value = 0.1285
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.933576 1.719189
## sample estimates:
## ratio of variances 
##           1.266883</code></pre>
<p>The output indicates that the default test compares the equality of
variances to the scenario where variances are unequal, given that the
ratio of variances differs from 1, our reference value. The confidence
interval of the ratio of true variances contains our reference value 1.
This suggests that, within the calculated confidence interval, there is
no significant evidence to conclude that the variances are different
from each other.</p>
<p>Using the proof of contradiction, the ratio we have observed based on
our data falls within the expected distribution of the ratio of two
variances when they are equal (p-value = 0.1285): this suggests that
there is no substantial evidence to refute the assumption of equal
variances based on the observed data.</p>
</div>
<div id="comparing-two-means" class="section level3">
<h3>Comparing two means</h3>
<p>Similarly to the comparison of two variances, comparing the means
associated with the two habits raises the question of whether the means
depends on the habits or not. Therefore, we use the same syntax to
compare two means as we do to compare two variances, but with the
<code>t.test()</code> function, specifying that the comparison is made
on the assumption that the variances are equal.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Score <span class="sc">~</span> Habit, <span class="at">var.equal =</span> <span class="cn">TRUE</span>, data_plane_unplug)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Score by Habit
## t = 6.1217, df = 332, p-value = 2.611e-09
## alternative hypothesis: true difference in means between group never_airplane_score and group unplug_score is not equal to 0
## 95 percent confidence interval:
##  0.6989826 1.3608976
## sample estimates:
## mean in group never_airplane_score         mean in group unplug_score 
##                           2.676647                           1.646707</code></pre>
<p>As mentionned previously, two values can be compared either by
calculating their difference or by calculating their ratio. Comparing
two means is done by calculating their difference and comparing this
difference to a reference value which is 0. This time, the confidence
interval calculated is that around the difference between the true
means. To obtain this interval, we need to estimate this difference and,
as before, estimate the variance of the difference between the means. To
estimate this variance, it is necessary to test for equality of
variances, as was done previously.</p>
<p>Several elements of the output indicate that the difference between
the true means is different from 0. The confidence interval around the
true mean does not contain the reference value. The p-value is much
smaller than 0.05, meaning that we can reject the null hypothesis, and
accept the alternative hypothesis. All of this is, of course, consistent
with the fact that what has been observed is far from the reference
situation, the true means are equal, in terms of the number of standard
deviations (t = 6.12).</p>
<p>Therefore, the perceptions of constraint of never taking an airplane,
and unplugging one’s electric device are not equal. Looking at the mean
values of each habit, we can assume that never riding an airplane is
considered more constraining than unplugging your electrical
devices.</p>
</div>
</div>
<div id="vocabulary-of-this-session" class="section level2">
<h2>Vocabulary of this session</h2>
<div id="r-commands" class="section level3">
<h3>R commands</h3>
<ul>
<li>library</li>
</ul>
</div>
<div id="r-environment" class="section level3">
<h3>R environment</h3>
<ul>
<li>packages</li>
</ul>
</div>
<div id="statistical-terms" class="section level3">
<h3>Statistical terms</h3>
<ul>
<li>Counting frequencies</li>
<li>Calculating the mean value</li>
</ul>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
